### PR TITLE
Refactor the CameraService

### PR DESCRIPTION
**Pull request by cobryan05**
A "small" change to refactor of the CameraService. It fixes many issues and hopefully adds very few.

This should decrease CPU usage and increase reliability.

I haven't yet ran this hooked up to the printer, but everything seems to be working well standalone.

### CODE REVIEW

**Comment by cobryan05** [comment]
Hmm, snapshots don't appear to be working on my Galaxy S5.  Flash goes off and it appears to go through the motions, but no data is returned. It worked on my BLU View 4 that I developed it on...

**Comment by cobryan05** [comment]
This overall seems to be working except the preview window seems to have some issues with the flash. 

Known issues:
* If the flash is on, it will be work the first time you open the preview window but not only briefly after you open/close the preview window. Also, the Preview window being open seems to prevent flash working for snapshot or stream (until you close the preview window).

* MJPEG still looks like it is periodically autofocusing on my Galaxy S5 despite the 'disable AF' being checked.

**Comment by feelfreelinux** [comment]
This is an amazing contribution, thanks a lot for your work! I'll review and test it out this week

**Comment by cobryan05** [comment]
This might be about as good as it gets for now. I kind of suspect some of the remaining issues may just be CameraX 1.0.0.

1. Preview Window flash weirdness:
   * On my dev phone (a $30 BluView4 tracphone) the preview window flash works, but it stays on for 10 seconds after closing the preview window (the call to enableTorch(false) is ignored, and then the flash turns off 10 seconds later when the camera unbinds, despite the Preview use case making no reference to flash).

   * On my Galaxy S5 (phone connected to the printer), the flash is pretty unreliable with the preview window. Sometimes it works, sometimes it doesn't. Sometimes having the preview window up makes flash from remote viewing not work. However, it all seems to go away when the preview window is closed.

I've given it my best shot to get it working properly, but it acts differently between devices and only affects the preview window, so it may just be what it is.

2. Autofocus:
   * I'm pretty sure my Galaxy S5 is ignoring my requests to turn off autofocus. Maybe other phones won't?

3. Flash can get stuck on
   * Sometime a mjpeg stream doesn't get properly unregistered and the flash gets stuck on because it thinks there is still a stream going

I'm interested to hear how it runs for you.   It's definitely not perfect, but I think it's an improvement.

**Comment by cobryan05** [comment]
Ugh, test print kept putting camera in error state.

**Comment by cobryan05** [comment]
It's actually is working really well right now, just from re-adding that super.onImageCaptureSuccess ... I have no idea why. Even looking through the CameraX source history I can't find any period of time in which it should matter...

**Comment by cobryan05** [comment]
At this point I am convinced that my Galaxy S5 simply doesn't support disabling autofocus.

ImageCapture still sometimes gets triggered when disabling the flash (probably if the ImageCapture was the last to unreference the flash).  Sometimes when this happens the flash will go off, even if you have a live stream going. In this case to get the flash back you'll need to either: 1. Wait for the next snapshot to re-enable the flash and hope it doesn't turn it off, or 2. Close all streams and re-open them.

I made it through an entire test print, continually stopping and starting live streams and snapshots, and it successfully complete with all timelapse images successful.  If this continues to work through the weekend I am going to call this "good enough to submit."

**Review by feelfreelinux — APPROVED** [review]
LGTM

**Comment by feelfreelinux** [comment]
Tested it out in an emulator and a Google Pixel XL phone - works well in both cases, I can see quite a bit of performance improvements from the previous version. The autofocus issues were very much present in the earlier codebase too - they're quite specific to a given model phone / camera FW. I'll try to do some more testing of the autofocus logic - but so far, this is a massive improvement over the previous code, and I really appreciate the time spent on this refactor :)

**Comment by cobryan05** [comment]
Glad to hear the autofocus isn't just me.  I'd like for my timelapses to come out pretty, but that's in the 'cosmetic' bucket of my priority list. I'm glad this isn't causing a regression for people with other priorities.

Thanks for all of the work you put into putting octo4a together. Phones seem like the ideal platform for octoprint, with builtin USB, camera and flash, and its nice to be able to give my Galaxy S5 another lease on life

**Comment by feelfreelinux** [comment]
Changes moved to https://github.com/feelfreelinux/octo4a/pull/496. Thanks a lot for your contribution, it will make a huge difference to people using their phone's cameras :)

**Pull request closed without merging**
