### PR TITLE
Fix snapshot and previews orientation

### PR DESCRIPTION
**Pull request by ravikiranp123**
Fixes the orientation of snapshots and camera preview. Still buggy as this does not update orientation when device orientation changes. The current way to use it is to open the app in the same orientation it is going to be used in. If app is already open, it needs to be forc closed and reopened.

### CODE REVIEW

**Comment by ravikiranp123** [comment]
Needs more testing for when rotation is set in settings.

**Comment by ravikiranp123** [comment]
Works correctly when auto rotate is enabled. Snapshots are broken when auto rotate is disabled.

**Review by Jeyy1 — APPROVED** [review]

**Comment by barthez** [comment]
Hey @feelfreelinux, is there anything I can help you with releasing this? I can offer manual testing on my setup (Galaxy S8) if you can provide me with preview build.

**Comment by alufers** [comment]
Already fixed with other PR

**Pull request closed without merging**
